version: '3'
services:
    bodypix:
        image: bodypix
        build:
            context: ./bodypix
            dockerfile: ${DOCKERFILE_NVIDIA}
        networks:
            - fakecam
        ports:
            - ${PORT_BODYPIX}:9000
        shm_size: ${SHM_SIZE_BODYPIX}
        ulimits:
            memlock: -1
            stack: 67108864
        runtime: nvidia

    fakecam:
        image: fakecam
        build:
            context: ./fakecam
        networks:
            - fakecam
        volumes:
            - ${IMAGE_BACKGROUND}:/src/background-custom:ro
            - ${IMAGE_FOREGROUND}:/src/foreground-custom:ro
            - ${IMAGE_FOREGROUND_MASK}:/src/foreground-mask-custom:ro
        devices:
            - ${VIDEO_INPUT}:/dev/video0
            - ${VIDEO_OUTPUT}:/dev/video2
        depends_on:
            - bodypix
        command: ["--bodypix-url", "http://bodypix:9000/",
                  "-b", "background-custom", "-f", "foreground-custom", "-m", "foreground-mask-custom",
                  "--webcam-path", "/dev/video0", "--v4l2loopback-path", "/dev/video2",
                  "--scale-factor", "1",]
networks:
    fakecam:
